# Generated by Django 4.1.2 on 2024-04-18 07:13

import apis.notifications.enum
import datetime
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_product_date_of_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "status",
                    enumchoicefield.fields.EnumChoiceField(
                        default=apis.notifications.enum.StatusEnum(1),
                        enum_class=apis.notifications.enum.StatusEnum,
                        max_length=6,
                    ),
                ),
                ("number_days_activate", models.IntegerField(default=0)),
                ("number_days_have_passed", models.IntegerField(default=0)),
                ("date_activate", models.DateField(default=datetime.datetime.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
