# Generated by Django 4.1.2 on 2024-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_of_expiry",
            field=models.DateField(null=True),
        ),
    ]
